name: Build and deploy ASP.Net Core app to Azure Web App - restorebydjoka

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET Core SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '3.1'

      - name: Restore dependencies
        run: dotnet restore src/RestoreByDjoka/RestoreByDjoka.csproj

      - name: Build project
        run: dotnet build src/RestoreByDjoka/RestoreByDjoka.csproj --configuration Release --no-restore

      - name: Publish project
        run: dotnet publish src/RestoreByDjoka/RestoreByDjoka.csproj --configuration Release --output ./publish --no-build

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ./publish

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build
        uses: actions/download-artifact@v4
        with:
          name: .net-app
          path: ./publish

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_8001F43660AE424DA7B96B7769D013CA }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_1DE82E63B3B648639C8AC625B90CA1CD }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_292A210EF0424C1A9B217FC6CC61E0B4 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'restorebydjoka'
          slot-name: 'Production'
          package: ./publish
